-- Add OAuth provider IDs and 2FA fields to User table

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "googleId" TEXT UNIQUE;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "vkId" TEXT UNIQUE;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorSecret" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false;
